name: Sync Develop with Master after Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout master
          git pull
          git checkout develop
          git merge -X theirs master -m="Sync develop with master"
          git push develop
