name: Sync Develop with Master after Release

on:
  release:
    types: [published]

jobs:
  merge-master-back-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Merge master back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to develop"
          git push
